# ODQ environments
# PostgreSQL
development:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: rdv_app_dev
  username: rdv_app
  password: rdv_app
  schema_search_path: "rdv_app"
  pool: 5

# TEST environment
# PostgreSQL
test:
  host: localhost 
  adapter: postgresql
  encoding: unicode
  database: rdv_app_test
  username: rdv_app
  password: rdv_app
  schema_search_path: "rdv_app"
  pool: 5
